// need to use this because wallet provider is not working on server side?
'use client'

// import type { Metadata, NextPage } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
// import { configureConnection } from '@puzzlehq/sdk'

import { ReactNode, useEffect, useMemo } from 'react'
import { WalletProvider } from '@demox-labs/aleo-wallet-adapter-react'
import { WalletModalProvider } from '@demox-labs/aleo-wallet-adapter-reactui'
import { LeoWalletAdapter } from '@demox-labs/aleo-wallet-adapter-leo'
import {
  DecryptPermission,
  WalletAdapterNetwork,
} from '@demox-labs/aleo-wallet-adapter-base'
import { Header } from '@/app/components/Header'
import { program } from '@/app/config'

// Default styles that can be overridden by your app
require('@demox-labs/aleo-wallet-adapter-reactui/styles.css')

const inter = Inter({ subsets: ['latin'] })

// can't use metadata because of the "use client" above

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

interface RootLayoutProps {
  children: ReactNode
}

export default function RootLayout({
  children,
}: RootLayoutProps) {
  // configureConnection({
  //   dAppName: 'Test DApp',
  //   dAppDescription: 'Test dApp',
  //   dAppUrl: 'https://localhost:3000/',
  //   dAppIconURL: 'https://localhost:3000/',
  // })

  const wallets = useMemo(
    () => [
      new LeoWalletAdapter({
        appName: 'Leo D App',
      }),
    ],
    [],
  )

  return (
    <html lang="en">
    <WalletProvider
      wallets={wallets}
      decryptPermission={DecryptPermission.OnChainHistory}
      network={WalletAdapterNetwork.Testnet}
      programs={['credits.aleo', 'tok3n_1337_v002.aleo']}
      autoConnect
    >
      <WalletModalProvider>
        <body className={inter.className}>
        <Header />
        <main className="flex flex-col px-10">
          {children}
        </main>
        </body>
      </WalletModalProvider>
    </WalletProvider>
    </html>
  )
}
